---
- name: Get MongoDB
  apt:
    name: mongodb
    state: present
    update_cache: true
  tags: install

- name: Enable and start systemd service
  systemd:
    name: mongodb
    enabled: true
    state: started
  tags: install
