Vagrant.configure("2") do |config|

  config.vm.provider :libvirt do |v|
    v.memory = 1024
  end

  config.vm.define "dbserver" do |db|
    db.vm.box = "generic/ubuntu1604"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"

    db.vm.provision "ansible" do |ansible1|
      ansible1.playbook = "playbooks/site.yml"
      ansible1.groups = {
      "db" => ["dbserver"],
      "db:vars" => {"mongo_bind_ip" => "0.0.0.0"}
      }
    end
  end

  config.vm.define "appserver" do |app|
    app.vm.box = "generic/ubuntu1604"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"

    app.vm.provision "ansible" do |ansible2|
      ansible2.playbook = "playbooks/site.yml"
      ansible2.groups = {
      "app" => ["appserver"],
      "app:vars" => {
          "db_host" => "10.10.10.10"
        }
      }
      ansible2.extra_vars = {
        "deploy_user" => "vagrant",
        nginx_sites: {
          default: ["listen 80", "server_name 'puma'", "location / {proxy_pass http://127.0.0.1:9292;}"]
        }
      }
    end
  end
end
